CREATE TABLE [dbo].[Save]
(
	[Id] BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1),

	[Uid] UNIQUEIDENTIFIER NOT NULL UNIQUE,
	
	[GameID] BIGINT NOT NULL  FOREIGN KEY REFERENCES [dbo].[Game]([Id]), 

	[SaveData] VARBINARY(MAX) NOT NULL,

	[SaveName] VARCHAR(512) NOT NULL
)
